NotOurStackOverflow/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NotOurStackOverflow.Models;
using NotOurStackOverflow.Models.Helpers;

namespace NotOurStackOverflow.Controllers
{
    public class AnswersController : Controller
    {
        private ApplicationDbContext db;
        private DBDataAccess dataAccess;
        private BusinessLogic businessLogic;

        public AnswersController()
        {
            db = new ApplicationDbContext();
            dataAccess = new DBDataAccess(db);
            businessLogic = new BusinessLogic(dataAccess);
        }

        // GET: Answers
        public ActionResult Index()
        {
            var posts = db.Answers.Include(a => a.User).Include(a => a.Question);
            return View(posts.ToList());
        }

        // GET: Answers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // GET: Answers/Create
        public ActionResult Create(int qId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Register", "Account");
            }

            ViewBag.Question = businessLogic.GetQuestion(qId);
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(int qId, [Bind(Include = "Id,Body,QuestionId")] Answer answer)
        {
            answer.UserId = User.Identity.GetUserId();
            answer.DatePosted = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Posts.Add(answer);
                db.SaveChanges();
                var question = businessLogic.GetQuestion(answer.QuestionId);
                question.Answers.Add(answer);
                db.SaveChanges();
                return RedirectToAction("Details", "Questions", new { id = answer.QuestionId });
            }

            ViewBag.Question = businessLogic.GetQuestion(qId);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", answer.UserId);
            ViewBag.QuestionId = new SelectList(db.Posts, "Id", "UserId", answer.QuestionId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,DatePosted,Body,QuestionId")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", answer.UserId);
            ViewBag.QuestionId = new SelectList(db.Posts, "Id", "UserId", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = db.Answers.Find(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Answer answer = db.Answers.Find(id);
            db.Posts.Remove(answer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NotOurStackOverflow/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NotOurStackOverflow.Models;
using NotOurStackOverflow.Models.Helpers;

namespace NotOurStackOverflow.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db;
        private DBDataAccess dataAccess;
        private BusinessLogic businessLogic;

        public CommentsController()
        {
            db = new ApplicationDbContext();
            dataAccess = new DBDataAccess(db);
            businessLogic = new BusinessLogic(dataAccess);
        }

        // GET: Comments
        public ActionResult Index()
        {
            var posts = db.Comments.Include(c => c.User).Include(c => c.Post);
            return View(posts.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create(int qId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Register", "Account");
            }

            var post = businessLogic.GetPost(qId);
            if(post is Question)
            {
                var question = (Question)post;
                ViewBag.PTitle = question.Title;
            }
            ViewBag.Post = post;
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(int qId, [Bind(Include = "Id,Body,PostId")] Comment comment)
        {
            comment.UserId = User.Identity.GetUserId();
            comment.DatePosted = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.Posts.Add(comment);
                db.SaveChanges();
                var commentPost = businessLogic.GetPost(comment.PostId);
                if (commentPost is Answer)
                {
                    Answer answer = (Answer)commentPost;
                    answer.Comments.Add(comment);
                }
                else
                {
                    Question question = (Question)commentPost;
                    question.Comments.Add(comment);
                }
                db.SaveChanges();
                if(comment.Post is Answer)
                {
                    Answer answer = (Answer)comment.Post;

                    return RedirectToAction("Details", "Questions", new { id = answer.QuestionId });
                } else
                {
                    return RedirectToAction("Details", "Questions", new { id = comment.PostId });
                }
            }

            var post = businessLogic.GetPost(qId);
            if (post is Question)
            {
                var question = (Question)post;
                ViewBag.PTitle = question.Title;
            }
            ViewBag.Post = post;
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Include(x => x.Votes).FirstOrDefault(p => p.Id == id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", comment.UserId);
            ViewBag.PostId = new SelectList(db.Posts, "Id", "UserId", comment.PostId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,DatePosted,Body,PostId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", comment.UserId);
            ViewBag.PostId = new SelectList(db.Posts, "Id", "UserId", comment.PostId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Posts.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NotOurStackOverflow/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NotOurStackOverflow.Models;
using NotOurStackOverflow.Models.Helpers;
using NotOurStackOverflow.Models.ViewModels;

namespace NotOurStackOverflow.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db;
        private DBDataAccess dataAccess;
        private BusinessLogic businessLogic;

        public TagsController()
        {
            db = new ApplicationDbContext();
            dataAccess = new DBDataAccess(db);
            businessLogic = new BusinessLogic(dataAccess);
        }
        // GET: Tags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // GET: Tags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult TagsQuestions(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tag = db.Tags.Find(Id);
            if (tag == null)
            {
                return HttpNotFound();
            }

            var QuestionList = db.Questions.Include("Votes").Where(x => x.Tags.Any(i => i.Id == tag.Id)).ToList();

            TagQuestionsViewModel tagQuestionsViewModel = new TagQuestionsViewModel
            {
                AllQuestions = QuestionList,
                PageTag = tag,
            };
            return View(tagQuestionsViewModel);
        }

        [HttpPost]
        public ActionResult TagsQuestions(int postId, bool isPositive, int currentTagId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Register", "Account");
            }


            Post post = db.Posts.Include(x => x.Votes).FirstOrDefault(p => p.Id == postId);
            ApplicationUser votingUser = db.Users.Find(User.Identity.GetUserId());
            ApplicationUser votedUser = db.Users.Find(post.UserId);
            Tag currentTag = db.Tags.Find(currentTagId);

            if (post == null || votingUser == null || votedUser == null || currentTag == null)
            {
                return HttpNotFound();
            }

            Vote newVote = new Vote
            {
                IsUpVote = isPositive,
                Post = post,
                PostId = post.Id,
                VotingUser = votingUser,
                VotingUserId = votingUser.Id,
                PostUser = votedUser,
                PostUserId = votedUser.Id,
            };

            var negatingVote = post.Votes.Where(v => v.VotingUserId == votingUser.Id && v.IsUpVote != newVote.IsUpVote).FirstOrDefault();
            db.Votes.Add(newVote);
            db.SaveChanges();

            post.Votes.Add(newVote);
            votingUser.VoteMade.Add(newVote);
            votedUser.VoteRecieved.Add(newVote);
            db.SaveChanges();

            if (negatingVote != null)
            {
                db.Votes.Remove(negatingVote);
                db.SaveChanges();
            }

            votedUser.Reputation = businessLogic.TabulateReputation(votedUser.Id);
            db.SaveChanges();
            return RedirectToAction("TagsQuestions", new { Id = currentTag.Id });
        }
    }
}

NotOurStackOverflow/Views/Tags/Create.cshtml
@model NotOurStackOverflow.Models.Tag

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tag</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotOurStackOverflow/Views/Tags/Delete.cshtml
@model NotOurStackOverflow.Models.Tag

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tag</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NotOurStackOverflow/Views/Tags/Details.cshtml
@model NotOurStackOverflow.Models.Tag

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tag</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NotOurStackOverflow/Views/Tags/Edit.cshtml
@model NotOurStackOverflow.Models.Tag

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tag</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotOurStackOverflow/Views/Tags/Index.cshtml
@model IEnumerable<NotOurStackOverflow.Models.Tag>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

NotOurStackOverflow/Views/Tags/TagsQuestions.cshtml
@model NotOurStackOverflow.Models.ViewModels.TagQuestionsViewModel
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "TagsQuestions";
}

<h2>@Model.PageTag.Title</h2>

<hr />

<div>
    @foreach (var r in Model.AllQuestions)
    {
        <div class="card w-auto margin-bottom" style="margin-bottom:10px; margin-top:10px">
            <div class="card-header">
                <div class="row">
                    <div class="col">@r.User.UserName | @r.User.Reputation</div>
                    <div class="col text-right">@r.DatePosted</div>
                </div>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    @Html.ActionLink(r.Title, "Details", "Questions", new { Id = r.Id }, new { @class = "question-title-link" })
                </h5>
            </div>
            <div class="card-footer text-muted container">
                <div class="row">
                    <div class="col-sm">
                        @foreach (var t in r.Tags)
                        {
                            <div class="badge badge-pill badge-secondary">
                                @Html.ActionLink((string)t.Title, "TagsQuestions", "Tags", new { Id = t.Id }, new { @style = "color:white;" })
                                @* Link to tag with list of questions *@
                            </div>
                        }
                    </div>

                    <div class="col-sm row align-items-sm-end justify-content-sm-end">

                        <div class="col-3">
                            @if (!r.Votes.Any(x => x.IsUpVote && x.VotingUserId == User.Identity.GetUserId()))
                            {
                                using (Html.BeginForm(FormMethod.Post))
                                {
                                    @Html.Hidden("isPositive", true)
                                    @Html.Hidden("postId", r.Id)
                                    @Html.Hidden("currentTagId", Model.PageTag.Id)
                                    <button type="submit" class="btn btn-success" value="@r.Votes.Where(x => x.IsUpVote).Count()  ++">
                                        ++ <span class="badge badge-light">@r.Votes.Where(x => x.IsUpVote).Count()</span>
                                    </button>
                                }
                            }
                            else
                            {
                                <button type="submit" class="btn btn-success" value="@r.Votes.Where(x => x.IsUpVote).Count()  ++" disabled>
                                    ++ <span class="badge badge-light">@r.Votes.Where(x => x.IsUpVote).Count()</span>
                                </button>
                            }

                        </div>
                        <div class="col-3">
                            @if (!r.Votes.Any(x => !x.IsUpVote && x.VotingUserId == User.Identity.GetUserId()))
                            {
                                using (Html.BeginForm(FormMethod.Post))
                                {
                                    @Html.Hidden("isPositive", false)
                                    @Html.Hidden("postId", r.Id)
                                    @Html.Hidden("currentTagId", Model.PageTag.Id)
                                    <button type="submit" class="btn btn-danger" value="@r.Votes.Where(x => !x.IsUpVote).Count()  ++">
                                        -- <span class="badge badge-light">@r.Votes.Where(x => !x.IsUpVote).Count()</span>
                                    </button>
                                }
                            }
                            else
                            {
                                <button type="submit" class="btn btn-danger" value="@r.Votes.Where(x => !x.IsUpVote).Count()  ++" disabled>
                                    -- <span class="badge badge-light">@r.Votes.Where(x => !x.IsUpVote).Count()</span>
                                </button>
                            }

                        </div>
                    </div>
                </div>
                <div class="row col-sm justify-content-end" style="margin-top:5px">
                    <div>
                        @Html.ActionLink("Answer", "Create", "Answers", new { qId = r.Id }, null) (@r.Answers.Count()) || @Html.ActionLink("Comment", "Create", "Comments", new { qId = r.Id }, null) (@r.Comments.Count())
                    </div>
                </div>
            </div>
        </div>
    }
</div>