NotOurStackOverflow/Models/ViewModels/LandingPageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NotOurStackOverflow.Models.ViewModels
{
    public class LandingPageViewModel
    {
        public ApplicationUser CurrentUser { get; set; }
        public ICollection<Question> AllQuestions { get; set; }
        public ICollection<Question> CurrentUserQuestions { get; set; }
        public int Page { get; set; }
        public string sortMethod { get; set; }

        public LandingPageViewModel()
        {

        }
    }
}

NotOurStackOverflow/Controllers/QuestionsController.cs
using Microsoft.AspNet.Identity;
using NotOurStackOverflow.Models;
using NotOurStackOverflow.Models.Helpers;
using NotOurStackOverflow.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace NotOurStackOverflow.Controllers
{
    public class QuestionsController : Controller
    {
        private ApplicationDbContext db;
        private DBDataAccess dataAccess;
        private BusinessLogic businessLogic;

        public QuestionsController()
        {
            db = new ApplicationDbContext();
            dataAccess = new DBDataAccess(db);
            businessLogic = new BusinessLogic(dataAccess);
        }

        // GET: Questions
        public ActionResult Index()
        {
            var posts = db.Questions.Include(q => q.User);
            return View(posts.ToList());
        }

        // add a GET to alter the ordering
        public ActionResult LandingPage(int? page, string sort)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            List<Question> usersQuestions = new List<Question>();
            List<Question> allQuestions = new List<Question>();

            if (user != null)
            {
                usersQuestions = businessLogic.AllUserQuestions(user.Id);
                allQuestions = businessLogic.GetQuestionsThatArentUsers(user.Id);
            }
            else
            {
                allQuestions = businessLogic.AllQuestions();
            }
            int viewPage = page == null ? 1 : (int)page;
            string Sort = sort == null ? "new" : sort;
            if (Sort == "Popular")
            {
                allQuestions = allQuestions.OrderByDescending(q => q.Answers.Count + q.Comments.Count).ToList();
            }
            else if (Sort == "OfDay")
            {
                var today = DateTime.Today;

                allQuestions = allQuestions.OrderByDescending(
                    q => q.Answers.Where(a => a.DatePosted.Value.Date == today).ToList().Count +
                    q.Comments.Where(c => c.DatePosted.Value.Date == today).ToList().Count).ToList();
            }
            else
            {
                allQuestions = allQuestions.OrderByDescending(q => q.DatePosted.Value).ToList();
            }
            ViewBag.AllQNum = allQuestions.Count;
            LandingPageViewModel viewModel = new LandingPageViewModel
            {
                CurrentUser = user,
                AllQuestions = allQuestions.Skip((viewPage - 1) * 10).Take(10).ToList(),
                CurrentUserQuestions = usersQuestions,
                Page = viewPage,
                sortMethod = Sort,
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult LandingPage(int postId, string userId, bool isPositive)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Register", "Account");
            }

            string newUserId = User.Identity.GetUserId();

            Post post = db.Posts.Include(x => x.Votes).FirstOrDefault(p => p.Id == postId);
            ApplicationUser votingUser = db.Users.Find(newUserId);
            ApplicationUser votedUser = db.Users.Find(post.UserId);

            if (post == null || votingUser == null || votedUser == null)
            {
                return HttpNotFound();
            }

            Vote newVote = new Vote
            {
                IsUpVote = isPositive,
                Post = post,
                PostId = post.Id,
                VotingUser = votingUser,
                VotingUserId = votingUser.Id,
                PostUser = votedUser,
                PostUserId = votedUser.Id,
            };

            var negatingVote = post.Votes.Where(v => v.VotingUserId == votingUser.Id && v.IsUpVote != newVote.IsUpVote).FirstOrDefault();
            db.Votes.Add(newVote);
            db.SaveChanges();

            post.Votes.Add(newVote);
            votingUser.VoteMade.Add(newVote);
            votedUser.VoteRecieved.Add(newVote);
            db.SaveChanges();

            if (negatingVote != null)
            {
                db.Votes.Remove(negatingVote);
                db.SaveChanges();
            }

            votedUser.Reputation = businessLogic.TabulateReputation(votedUser.Id);
            db.SaveChanges();

            return RedirectToAction("_OtherUserQuestions");
        }

        public PartialViewResult _OtherUserQuestions()
        {
            var allQuestions = businessLogic.GetQuestionsThatArentUsers(User.Identity.GetUserId());
            return PartialView("_OtherUserQuestions", allQuestions);
        }

        // GET: Questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Include(x => x.Votes).FirstOrDefault(p => p.Id == id);
            foreach (Post p in db.Posts)
            {
                db.Entry(p).Collection(x => x.Votes).Load();
            }
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        [HttpPost]
        public ActionResult Details(int? id, int postId, bool isPositive)
        {
            // create a vote the the accepted parameters
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Register", "Account");
            }

            Question currentQuestion = db.Questions.Include(p => p.Comments).Include(x => x.Votes).Include(p => p.Answers).First(x => x.Id == id);
            foreach (Post p in db.Posts)
            {
                db.Entry(p).Collection(x => x.Votes).Load();
            }
            Post post = db.Posts.Include(x => x.Votes).FirstOrDefault(p => p.Id == postId);
            ApplicationUser votingUser = db.Users.Find(User.Identity.GetUserId());
            ApplicationUser votedUser = db.Users.Find(post.UserId);

            if (post == null || votingUser == null || votedUser == null)
            {
                return HttpNotFound();
            }

            Vote newVote = new Vote
            {
                IsUpVote = isPositive,
                Post = post,
                PostId = post.Id,
                VotingUser = votingUser,
                VotingUserId = votingUser.Id,
                PostUser = votedUser,
                PostUserId = votedUser.Id,
            };

            var negatingVote = post.Votes.Where(v => v.VotingUserId == votingUser.Id && v.IsUpVote != newVote.IsUpVote).FirstOrDefault();
            db.Votes.Add(newVote);
            db.SaveChanges();

            post.Votes.Add(newVote);
            votingUser.VoteMade.Add(newVote);
            votedUser.VoteRecieved.Add(newVote);
            db.SaveChanges();

            if (negatingVote != null)
            {
                db.Votes.Remove(negatingVote);
                db.SaveChanges();
            }

            votedUser.Reputation = businessLogic.TabulateReputation(votedUser.Id);
            db.SaveChanges();

            return RedirectToAction("_FullQuestion", new { questionId = currentQuestion.Id });
        }

        public PartialViewResult _FullQuestion(int questionId)
        {
            Question currentQuestion = db.Questions.Include(p => p.Comments).Include(x => x.Votes).Include(p => p.Answers).First(x => x.Id == questionId);
            foreach (Post p in db.Posts)
            {
                db.Entry(p).Collection(x => x.Votes).Load();
            }
            return PartialView("_FullQuestion", currentQuestion);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Register", "Account");
            }

            ViewBag.TagId = new MultiSelectList(db.Tags, "Id", "Title");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(List<int> TagId, string body, string Title, string NewTagName)
        {
            Question question = new Question
            {
                Body = body,
                Tags = new List<Tag>(),
                Title = Title,
            };
            if (TagId != null)
            {
                foreach (var tagId in TagId)
                {
                    question.Tags.Add(db.Tags.Find(tagId));
                }
            }

            if (!string.IsNullOrWhiteSpace(NewTagName))
            {
                Tag NewTag = new Tag();
                NewTag.Title = NewTagName;

                db.Tags.Add(NewTag);
                db.SaveChanges();
                question.Tags.Add(NewTag);
            }
            question.UserId = User.Identity.GetUserId();
            question.DatePosted = DateTime.Now;
            db.SaveChanges();
            if (ModelState.IsValid)
            {
                db.Posts.Add(question);
                db.SaveChanges();
                return RedirectToAction("LandingPage");
            }
            return View(question);
        }

        // GET: Questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

NotOurStackOverflow/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NotOurStackOverflow.Models;
using NotOurStackOverflow.Models.Helpers;
using NotOurStackOverflow.Models.ViewModels;

namespace NotOurStackOverflow.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db;
        private DBDataAccess dataAccess;
        private BusinessLogic businessLogic;

        public TagsController()
        {
            db = new ApplicationDbContext();
            dataAccess = new DBDataAccess(db);
            businessLogic = new BusinessLogic(dataAccess);
        }
        // GET: Tags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // GET: Tags/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult TagsQuestions(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tag = db.Tags.Find(Id);
            if (tag == null)
            {
                return HttpNotFound();
            }

            var QuestionList = db.Questions.Include("Votes").Where(x => x.Tags.Any(i => i.Id == tag.Id)).ToList();

            TagQuestionsViewModel tagQuestionsViewModel = new TagQuestionsViewModel
            {
                AllQuestions = QuestionList,
                PageTag = tag,
            };
            return View(tagQuestionsViewModel);
        }

        [HttpPost]
        public ActionResult TagsQuestions(int postId, bool isPositive, int currentTagId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Register", "Account");
            }


            Post post = db.Posts.Include(x => x.Votes).FirstOrDefault(p => p.Id == postId);
            ApplicationUser votingUser = db.Users.Find(User.Identity.GetUserId());
            ApplicationUser votedUser = db.Users.Find(post.UserId);
            Tag currentTag = db.Tags.Find(currentTagId);

            if (post == null || votingUser == null || votedUser == null || currentTag == null)
            {
                return HttpNotFound();
            }

            Vote newVote = new Vote
            {
                IsUpVote = isPositive,
                Post = post,
                PostId = post.Id,
                VotingUser = votingUser,
                VotingUserId = votingUser.Id,
                PostUser = votedUser,
                PostUserId = votedUser.Id,
            };

            var negatingVote = post.Votes.Where(v => v.VotingUserId == votingUser.Id && v.IsUpVote != newVote.IsUpVote).FirstOrDefault();
            db.Votes.Add(newVote);
            db.SaveChanges();

            post.Votes.Add(newVote);
            votingUser.VoteMade.Add(newVote);
            votedUser.VoteRecieved.Add(newVote);
            db.SaveChanges();

            if (negatingVote != null)
            {
                db.Votes.Remove(negatingVote);
                db.SaveChanges();
            }

            votedUser.Reputation = businessLogic.TabulateReputation(votedUser.Id);
            db.SaveChanges();
            return RedirectToAction("TagsQuestions", new { Id = currentTag.Id });
        }
    }
}

NotOurStackOverflow/Views/Questions/ACCreate.cshtml
@model NotOurStackOverflow.Models.Post

@{
    ViewBag.Title = "ACCreate";
}

<h2>Answer & Comment Create</h2>
@if (ViewBag.Question != null)
{
    <div>
        <h3>@ViewBag.Question.Title</h3>
        <p>@ViewBag.Question.Title</p>
    </div>
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NotOurStackOverflow/Views/Questions/Create.cshtml
@model NotOurStackOverflow.Models.Question

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div @*class="form-horizontal"*@>
        <h4>Question</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="rounded">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="rounded">
                @Html.TextAreaFor(model => model.Body, 10, 975, new { htmlAttributes = new { style = "rounded" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Tags:</label>
            <div class="col-md-10">
                @Html.ListBox("TagId", (MultiSelectList)ViewBag.ListTest, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">(Optional)New Tag:</label>
            <div class="col-md-10">
                @Html.TextBox("NewTagName")
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<script src="~/Content/MultiSelect.js"></script>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/tinymce/tinymce.js"></script>
    <script src="~/Scripts/Main.js"></script>
}

NotOurStackOverflow/Views/Questions/Delete.cshtml
@model NotOurStackOverflow.Models.Question

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePosted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatePosted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NotOurStackOverflow/Views/Questions/Details.cshtml
@model NotOurStackOverflow.Models.Question
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
}

<body>

    @{
        Html.RenderPartial("_FullQuestion", Model);
    }

</body>

NotOurStackOverflow/Views/Questions/LandingPage.cshtml
@model NotOurStackOverflow.Models.ViewModels.LandingPageViewModel
    @using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "LandingPage";
}

@if (Model.CurrentUser != null)
{
    <h3>Welcome Home, @Model.CurrentUser.UserName. We've missed you.</h3>
}
else
{
    <h4>@Html.ActionLink("Sign up with NOSO", "Register", "Account") to start asking questions, giving answers, voting, and earning reputation.</h4>
}

@if (Model.CurrentUserQuestions.Any())
{
    <div style="margin-bottom:10px">Have a look at how your current questions are doing:</div>
    <div>
        @foreach (var q in Model.CurrentUserQuestions)
        {
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">@q.User.UserName | @q.User.Reputation</div>
                        <span>@q.DatePosted</span>
                    </div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        @Html.ActionLink(q.Title, "Details", "Questions", new { Id = q.Id }, new { @class = "question-title-link" })
                    </h5>
                </div>
                <div class="card-footer text-muted container">
                    <div class="row">
                        <div class="col-sm">
                            @foreach (var t in q.Tags)
                            {
                                <div class="badge badge-pill badge-secondary">
                                    @Html.ActionLink((string)t.Title, "TagsQuestions", "Tags", new { Id = t.Id }, new { @style = "color:white;" })
                                    @* Link to tag with list of questions *@
                                </div>
                            }
                        </div>

                        <div class="col-sm row align-items-sm-end justify-content-sm-end">
                            <div class="col-3">
                                <button type="submit" class="btn btn-success" disabled>
                                    ++ <span class="badge badge-light">@q.Votes.Where(x => x.IsUpVote).Count()</span>
                                </button>
                            </div>
                            <div class="col-3">
                                <button type="submit" class="btn btn-danger" disabled>
                                    -- <span class="badge badge-light">@q.Votes.Where(x => !x.IsUpVote).Count()</span>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="row col-sm justify-content-end" style="margin-top:5px">
                        <div>
                            Answer (@q.Answers.Count()) || Comment (@q.Comments.Count())
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}

<hr />

<div class="button-box">
    <button class="btn btn-outline-dark" onclick="location.href = '@Url.Action("LandingPage", "Questions", new {Page = Model.Page, sort="New" })'; return false;">Newest</button>
    <button class="btn btn-outline-dark" onclick="location.href = '@Url.Action("LandingPage", "Questions", new {Page = Model.Page, sort="Popular" })'; return false;">Most Popular</button>
    <button class="btn btn-outline-dark" onclick="location.href = '@Url.Action("LandingPage", "Questions", new {Page = Model.Page, sort="OfDay" })'; return false;">Qs and As of the Day</button>
</div>

@{ 
    Html.RenderPartial("_OtherUserQuestions", Model.AllQuestions);
}

<div class="page-box">
    @if (Model.Page > 1)
    {
        <button id="prev-ten" onclick="location.href='@Url.Action("LandingPage", "Questions", new {Page = Model.Page -1, sort=Model.sortMethod })';return false;"><<</button>
    }
    @if ((Model.Page + 1) < Math.Ceiling((decimal)(ViewBag.AllQNum / 10)))
    {
        <button id="next-ten" onclick="location.href = '@Url.Action("LandingPage", "Questions", new {Page = Model.Page +1, sort=Model.sortMethod })'; return false;">>></button>
    }
</div>

NotOurStackOverflow/Views/Questions/_OtherUserQuestions.cshtml
@model List<NotOurStackOverflow.Models.Question>
@using Microsoft.AspNet.Identity;
<div id="other-users">
    @foreach (var r in Model)
    {
        <div class="card w-auto margin-bottom" style="margin-bottom:10px; margin-top:10px">
            <div class="card-header">
                <div class="row">
                    <div class="col">@r.User.UserName | @r.User.Reputation</div>
                    <div class="col text-right">@r.DatePosted</div>
                </div>
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    @Html.ActionLink(r.Title, "Details", "Questions", new { Id = r.Id }, new { @class = "question-title-link" })
                </h5>
            </div>
            <div class="card-footer text-muted container">
                <div class="row">
                    <div class="col-sm">
                        @foreach (var t in r.Tags)
                        {
                            <div class="badge badge-pill badge-secondary">
                                @Html.ActionLink((string)t.Title, "TagsQuestions", "Tags", new { Id = r.Id }, new { @style = "color:white;" })
                                @* Link to tag with list of questions *@
                            </div>
                        }
                    </div>
                    <div class="col-sm row align-items-sm-end justify-content-sm-end">
                        <div class="col-3">
                            @if (!r.Votes.Any(x => x.IsUpVote && x.VotingUserId == User.Identity.GetUserId()))
                            {
                                using (Ajax.BeginForm("LandingPage", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "other-users", InsertionMode = InsertionMode.Replace }))
                                {
                                    @Html.Hidden("isPositive", true)
                                    @Html.Hidden("postId", r.Id)
                                    @Html.Hidden("userId", User.Identity.GetUserId())
                                    <button type="submit" class="btn btn-success" value="@r.Votes.Where(x => x.IsUpVote).Count()  ++">
                                        ++ <span class="badge badge-light">@r.Votes.Where(x => x.IsUpVote).Count()</span>
                                    </button>
                                }
                            }
                            else
                            {
                                <button type="submit" class="btn btn-success" value="@r.Votes.Where(x => x.IsUpVote).Count()  ++" disabled>
                                    ++ <span class="badge badge-light">@r.Votes.Where(x => x.IsUpVote).Count()</span>
                                </button>
                            }
                        </div>
                        <div class="col-3">
                            @if (!r.Votes.Any(x => !x.IsUpVote && x.VotingUserId == User.Identity.GetUserId()))
                            {
                                using (Ajax.BeginForm("LandingPage", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "other-users", InsertionMode = InsertionMode.Replace }))
                                {
                                    @Html.Hidden("isPositive", false)
                                    @Html.Hidden("postId", r.Id)
                                    @Html.Hidden("userId", User.Identity.GetUserId())
                                    <button type="submit" class="btn btn-danger" value="@r.Votes.Where(x => !x.IsUpVote).Count()  ++">
                                        -- <span class="badge badge-light">@r.Votes.Where(x => !x.IsUpVote).Count()</span>
                                    </button>
                                }
                            }
                            else
                            {
                                <button type="submit" class="btn btn-danger" value="@r.Votes.Where(x => !x.IsUpVote).Count()  ++" disabled>
                                    -- <span class="badge badge-light">@r.Votes.Where(x => !x.IsUpVote).Count()</span>
                                </button>
                            }
                        </div>
                    </div>
                </div>
                <div class="row col-sm justify-content-end" style="margin-top:5px">
                    <div>
                        @Html.ActionLink("Answer", "Create", "Answers", new { qId = r.Id }, null) (@r.Answers.Count()) || @Html.ActionLink("Comment", "Create", "Comments", new { qId = r.Id }, null) (@r.Comments.Count())
                    </div>
                </div>
            </div>
        </div>
    }
</div>